name: oauth2_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  # flutter:
  #   sdk: flutter
  # flutter_localizations:
  #   sdk: flutter
  # cupertino_icons: ^1.0.2
  # google_fonts: ^6.1.0
  # flutter_svg: ^2.0.9
  # flutter_riverpod: ^2.4.9
  # dotted_border: ^2.1.0
  # intl: ^0.19.0
  # image_picker: ^1.0.5
  # sizer: ^2.0.15
  # fluttertoast: ^8.2.4
  # pdf: ^3.10.7
  # printing: ^5.11.1
  # open_filex: ^4.3.4
  # path_provider: ^2.1.1
  # carousel_slider: ^5.0.0
  # smooth_page_indicator: ^1.1.0
  # cached_network_image: ^3.3.1
  # flutter_slidable: ^3.0.1
  # syncfusion_flutter_signaturepad: ^24.2.9
  # syncfusion_flutter_pdf: ^24.2.9
  # syncfusion_flutter_pdfviewer: ^24.2.8
  # syncfusion_flutter_charts: ^24.2.9
  # dio: ^5.4.1
  # riverpod_annotation: ^2.3.4
  # shared_preferences: ^2.2.2
  # go_router: ^14.2.0
  # rxdart: ^0.27.7
  # loading_animation_widget: ^1.2.1
  # http_parser: ^4.0.2
  # crypto: ^3.0.5
  # flutter_secure_storage: ^9.2.2
  # oauth2: ^2.0.3
  # webview_flutter: ^4.0.0
  # openid_client: ^0.4.8
  # base
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  # authentication
  openid_client: ^0.4.8
  url_launcher: ^6.3.1

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  # flutter_lints: ^4.0.0
  # riverpod_generator: ^2.3.11
  # build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.1
  custom_lint: ^0.6.8
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true
